### ISSUE TITLE
A realistic visibility tool for the STIS coronagraph

### ISSUE THREAD

**Issue by seawander** [spacetelescope/STIS-Notebooks#1]
Hi all,

To those who are interested in using a realistic visibility tool for the STIS coronagraph, you can visit my repo at https://github.com/seawander/VISIT-STIS-Coron 

The above tool uses the actual coronagraphic mask built by John Debes, then adopts the following actual measurements from my 2017 STIS coronagraphic archive study:
(1) Actual acquisition locations behind the coronagraphs
(2) Actual diffraction spike width for observation designing purposes
(3) Actual occulting location supported through the realistic mask
(4) Multi-orbit and multi-aperture visibility support
(5) `POSTARG` and `ORIENT` values supported in Phase 2 of the APT -- and sub pixel dithering is just a side product from the `POSTARG` parameter.

Thanks,
Bin Ren

**Comment by sosey** [comment]
closing in prep for archiving this repository. @sean-lockwood is there any information that should be replicated elsewhere? the referenced repository looks like it hasn't been updated in a few years.

**Comment by sean-lockwood** [comment]
@sosey 

This appears to add functionality over the current tool written by K. Ward-Duong in HST Notebooks (empirical mask and spike positions):
https://spacetelescope.github.io/hst_notebooks/notebooks/STIS/CoronagraphyViz/STIS_Coronagraphy_Visualization_v2.html

I'd suggest we open a Jira ticket to implement this functionality and ask the STIS team to prioritize adoption/implementation/testing.

**Comment by sosey** [comment]
Will you make the appropriate ticket in the ITC project? maybe off off itc-10?

**Comment by seawander** [comment]
> closing in prep for archiving this repository. @sean-lockwood is there any information that should be replicated elsewhere? the referenced repository looks like it hasn't been updated in a few years.

Thanks for the reply! Yeah I didn't update it, since it is in a mature stage and some of my colleagues have been using it. The only thing that I can think of is to speed up the rotation procedure of the mask array, but I do not know how to do it efficiently yet.

**Comment by sosey** [comment]
hi @seawander!  Got it.  One thing you could do, would be to run the code against the current minimum python version and packages that are imported to see if there are any language updates that need to be made. If you're still using it, it would be useful to add a github actions workflow that executed the code that way and reported issues it found, that will help keep it functional for anyone that finds it :)
